### ISSUE TITLE
TailFindR completing successfully but producing empty outputs

### ISSUE THREAD

**Issue by MoHeydarian-MS** [adnaniazi/tailfindr#40]
Hello,
Thank you for developing and maintaining TailFindR. 

We are having difficulty getting TailFindR to successfully run and provide the appropriate outputs on our data. We are able to get TailFindR to run and provide the appropriate outputs with some [publicly available data](https://github.com/Huanle/epinano1.2.0_test_data/tree/main/test_data/make_predictions/ko_fast5), but not with our own. 

We are working with direct RNA-seq data that has been live basecalled by MinKNOW using the FAST basecalling model (MinKNOW v21.05.13, MinKNOW Core v4.3.8, Bream v6.2.5, Guppy v5.0.12). We are using the latest version of Guppy (v6.3.7) to rebasecall these data with `--fast5_out` specified. We then use TailFindR while specifying `--basecall_group=Basecall_1D_001` and are not getting output .len or .csv populated with data. See below for commands, logs, and contents of the rebasecalled fast5 input data.  

This is the Guppy (v6.3.7) command used for rebasecalling:
```
guppy_basecaller -c rna_r9.4.1_70bps_fast.cfg -i <input> -s <output> -q 0 --disable_pings --num_callers 2 --cpu_threads_per_caller 6 --fast5_out
```

The rebasecalled data have the move, trace, and fastq information in the Basecall_1D_001 directory. Here is the contents of the rebasecalled fast5 file:
![Eno2 (fast live basecalling) rebasecalled fast5 file structure](https://user-images.githubusercontent.com/72889384/192876403-37fd7ddd-8f16-4825-8fdf-bc5b61247837.png)

Running TailFindR while specifying `--basecall_group=Basecall_1D_001` results in successful completion of TailFindR but with empty .len and a .csv missing the read_id, tail_start ,tail_end ,samples_per_nt ,tail_length data and only containing information in the file_path column. See the TailFindR log below:
```
--------------------------------------------------------------------------------
-- Started tailfindr (version 1.3) ---------------------------------------------
--------------------------------------------------------------------------------
= You have configured tailfindr as following:
> fast5_dir:         eno2
> save_dir:          ./
> csv_filename:      tailfindr_res.csv
> num_cores:         8
> basecall_group:    Basecall_1D_001
> save_plots:        FALSE
> plot_debug_traces: FALSE
> plotting_library:  rbokeh
-- Processing started at 2022-09-16 17:48:15 -----------------------------------
* Searching for all Fast5 files...
  Done! Found 1 Fast5 files.
* Analyzing a single Fast5 file to assess if your data 
  is in an acceptable format...
  v The data has been basecalled using Guppy.
  v Flipflop model was used during basecalling.
  v The reads are packed in multi-fast5 file(s).
  v The experiment type is RNA, so we will search
    for poly(A) tails.
  v The reads are 1D reads.
* Starting a parallel compute cluster...
  Done!
* Discovering reads in the 1 multifast5 files...
  Done! Found 1219 reads
* Searching for Poly(A) tails...
  Processing chunk 1 of 1
* Formatting the tail data...
  Done!
* Saving the data in the CSV file...
  Done! Below is the path of the CSV file:
  .//tailfindr_res.csv
* A logfile containing all this information has been saved in this path: 
  .//2022-09-16_17-48-15_tailfinder.log
-- Processing ended at 2022-09-16 17:48:23 -------------------------------------
v tailfindr finished successfully!
 A tibble: 1,219 x 6
   read_id tail_start tail_end samples_per_nt tail_length file_path             
   <lgl>   <lgl>      <lgl>             <dbl>       <dbl> <chr>                 
 1 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 2 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 3 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 4 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 5 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 6 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 7 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 8 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 9 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
10 NA      NA         NA                   NA          NA eno2/CTLeno2FAR71298_~
 ... with 1,209 more rows
```

We would be grateful for any insight and would be happy to share a bit of our data.

Thanks in advance for your help!

**Comment by adnaniazi** [comment]
Hi,

Thank you for trying out tailfindr.

Seem like you haven't installed VBZ plugin correctly. Please follow the instructions here:https://community.nanoporetech.com/posts/inspecting-fast5-from-flon
This should solve the problem.

Best,
Adnan

**Comment by zigavicic** [comment]
I've ran in the same problem today (had VBZ installed beforehand but reinstalled it just in case - didn't fix the problem)

**Comment by adnaniazi** [comment]
@zigavicic : does tailfindr work on the data that comes with the package itself. Can you test it?

**Comment by zigavicic** [comment]
Where can I find the fast5 files? The ones at tailfindr/inst/extdata/rna_basecall_1D_001/*.fast5 have been basecalled using MinKNOW and that doesn't seem to work (do I have to re-basecall them to reproduce this?)

**Comment by adnaniazi** [comment]
Just run:
library(tailfindr)
df <- find_tails(fast5_dir = system.file('extdata', 'rna', package = 'tailfindr'),
                 save_dir = '~/Downloads',
                 csv_filename = 'rna_tails.csv',
                 num_cores = 2)

**Comment by adnaniazi** [comment]
Because it works with data that comes with the package, it means the VBZ plugin is not installed/configured properly. Please follow the instructions here:https://community.nanoporetech.com/posts/inspecting-fast5-from-flon
This should solve the problem with your own data.

**Comment by zigavicic** [comment]
This issue was solved once I switched to our Linux system and re-produced the steps from [https://community.nanoporetech.com/posts/inspecting-fast5-from-flon](https://community.nanoporetech.com/posts/inspecting-fast5-from-flon ) so as far as this goes it works fine. Wonderful package!
